/*
 * Generated by ISE 6.0.6.9618 GPL Edition - windows
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"


#ifdef __cplusplus
extern "C" {
#endif

extern void Faao5tm();
extern EIF_BOOLEAN Faagrnj();
extern EIF_REFERENCE Faajcd0();
extern void Fhlw6xp();
extern void Fhognjg();
extern void Fe25cfl();
extern void Fhp6png();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) Faao5tm;
	egc_equal = (EIF_UNION (*)(EIF_REFERENCE, EIF_UNION, EIF_UNION)) Faagrnj;
	egc_twin = (EIF_UNION (*)(EIF_REFERENCE)) Faajcd0;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_UNION)) Fhlw6xp;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_UNION, EIF_UNION)) Fe25cfl;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_UNION)) Fhognjg;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_UNION, EIF_UNION, EIF_UNION, EIF_UNION, EIF_UNION, EIF_UNION, EIF_UNION, EIF_UNION, EIF_UNION, EIF_UNION, EIF_UNION, EIF_UNION)) Fhp6png;

	egc_str_dtype = 774;
	egc_arr_dtype = 1462;
	egc_tup_dtype = 726;
	egc_disp_rout_id = 9709;
	egc_bit_dtype = 137;

	egc_sp_char = (uint32)1521;
	egc_sp_wchar = (uint32)1640;
	egc_sp_bool = (uint32)1568;
	egc_sp_uint8 = (uint32)1496;
	egc_sp_uint16 = (uint32)1576;
	egc_sp_uint32 = (uint32)1572;
	egc_sp_uint64 = (uint32)1574;
	egc_sp_int8 = (uint32)1560;
	egc_sp_int16 = (uint32)1562;
	egc_sp_int32 = (uint32)1436;
	egc_sp_int64 = (uint32)1564;
	egc_sp_real32 = (uint32)1548;
	egc_sp_real64 = (uint32)1566;
	egc_sp_pointer = (uint32)1570;
	egc_sp_ref = (uint32)1467;

	egc_uint8_ref_dtype = 727;
	egc_uint16_ref_dtype = 754;
	egc_uint32_ref_dtype = 745;
	egc_uint64_ref_dtype = 763;
	egc_int8_ref_dtype = 730;
	egc_int16_ref_dtype = 748;
	egc_int32_ref_dtype = 736;
	egc_int64_ref_dtype = 751;
	egc_bool_ref_dtype = 742;
	egc_real32_ref_dtype = 757;
	egc_char_ref_dtype = 760;
	egc_wchar_ref_dtype = 733;
	egc_real64_ref_dtype = 739;
	egc_point_ref_dtype = 769;

	egc_uint8_dtype = 728;
	egc_uint16_dtype = 755;
	egc_uint32_dtype = 746;
	egc_uint64_dtype = 764;
	egc_int8_dtype = 731;
	egc_int16_dtype = 749;
	egc_int32_dtype = 737;
	egc_int64_dtype = 752;
	egc_bool_dtype = 743;
	egc_real32_dtype = 758;
	egc_char_dtype = 761;
	egc_wchar_dtype = 734;
	egc_real64_dtype = 740;
	egc_point_dtype = 770;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;

	egc_fcall = egc_fcall_init;
	egc_forg_table = egc_forg_table_init;
	egc_fdtypes = egc_fdtypes_init;

	egc_system_name = "ex_ev_7_control_structures";
	egc_system_location = "D:\\EiffelLab\\Traffic\\trunk\\example\\ex_ev_7_control_structures\\EIFGENs\\ex_ev_7_control_structures_structures\\W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1193911674;
	scount = 2346;

	egc_rcorigin = 1530;
	egc_rcdt = 0;
	egc_rcoffset = 0;
	egc_rcarg = 0;

	egc_platform_level = 0x00000D00;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt == 0) {
			egc_rcdt = 1978;
	}
}


#ifdef __cplusplus
}
#endif

